from django.db import models

# Create your models here.
class addrbook(models.Model):
    CntType=models.CharField(max_length=15)
    Full_Name=models.CharField(max_length=50)
    First_name=models.CharField(max_length=20)
    Middile_Name=models.CharField(max_length=20)
    Last_Name=models.CharField(max_length=20)
    Company=models.CharField(max_length=50)
    Designation=models.CharField(max_length=50)
    EmailID=models.EmailField(max_length=50)
    Phone=models.IntegerField()
    Location=models.CharField(max_length=50)
    Gender=models.CharField(max_length=1)
    Title=models.CharField(max_length=50)
    Dept=models.CharField(max_length=50)
    University=models.CharField(max_length=50)
    Degree=models.CharField(max_length=50)
    Passing_Year=models.IntegerField()
    College=models.CharField(max_length=50)
    LinkedIn_URL=models.CharField(max_length=50)
    Facebook_URL=models.CharField(max_length=50)
    SkypeID=models.CharField(max_length=50)
    Industry=models.CharField(max_length=50)
    Country=models.CharField(max_length=50)
    State=models.CharField(max_length=50)
    Zip=models.IntegerField()
    Key_Skills=models.CharField(max_length=200)
    Total_Exp=models.IntegerField()
    Years_in_Business=models.IntegerField()
    CIN_No=models.CharField(max_length=50)
    TurnOver=models.IntegerField()
    Date_of_Incorporation=models.DateField()
    Employees=models.IntegerField()
    CTC=models.IntegerField()
    #Docid_List=models.CharField(max_length=100)
    #GroupID=models.CharField(max_length=50)
    #SegmentID=models.CharField(max_length=50)
