# Generated by Django 3.1 on 2020-08-25 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20200825_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='meetings',
            fields=[
                ('mtgID', models.IntegerField(primary_key=True, serialize=False)),
                ('mtgTitle', models.CharField(max_length=50)),
                ('mtgDescription', models.CharField(max_length=100)),
                ('mtgDate', models.DateField()),
                ('mtgAttendees', models.CharField(max_length=500)),
                ('mtgTime', models.TimeField()),
                ('mtgType', models.CharField(max_length=20)),
                ('mtgAgenda', models.CharField(max_length=50)),
                ('mtgRemarks', models.CharField(max_length=50)),
                ('mtgReminderFreq', models.TimeField()),
                ('mtgLocation', models.CharField(max_length=20)),
                ('usrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
