# Generated by Django 3.1 on 2020-08-25 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20200825_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('frmID', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('frmName', models.CharField(max_length=20)),
                ('frmTitle', models.CharField(max_length=20)),
                ('frmCreatedOn', models.DateTimeField()),
                ('frmStatus', models.CharField(max_length=20)),
                ('frmGroup', models.CharField(max_length=20)),
                ('frmPublishDate', models.DateField()),
                ('frmEndDate', models.DateField()),
                ('frmURL', models.CharField(max_length=50)),
                ('frmDescription', models.CharField(max_length=100)),
                ('usrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
