# Generated by Django 3.1 on 2020-08-25 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20200825_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='cscore',
            fields=[
                ('csxID', models.IntegerField(primary_key=True, serialize=False)),
                ('csxName', models.CharField(max_length=50)),
                ('csxDescription', models.CharField(max_length=100)),
                ('csxCreatedOn', models.DateTimeField()),
                ('csxStatus', models.CharField(max_length=20)),
                ('usrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
