# Generated by Django 3.1 on 2020-08-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('usrID', models.IntegerField(primary_key=True, serialize=False)),
                ('usrName', models.CharField(max_length=50)),
                ('usrEmailID', models.EmailField(max_length=50)),
                ('usrDescription', models.CharField(max_length=100)),
                ('usrCreationDate', models.DateField()),
                ('usrStatus', models.IntegerField(max_length=1)),
                ('usrType', models.CharField(max_length=10)),
                ('usrPlan', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=25)),
                ('GoogleID', models.CharField(max_length=25)),
                ('LinkedIN', models.CharField(max_length=25)),
                ('usrPhone', models.IntegerField(max_length=10)),
                ('usrOrgName', models.CharField(max_length=50)),
            ],
        ),
    ]
