# Generated by Django 3.1 on 2020-08-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usrPhone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='usrStatus',
            field=models.IntegerField(),
        ),
    ]
